name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make
      run: make all
    - name: Run Binary
      run: ./export_csv
    - name: Show CSV
      run: cat ./example.csv
    - name: Copy CSV Files
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: |
          ./example.csv
